### ISSUE TITLE
部分国家或地区不填充黑色且科特迪瓦报错的问题

### ISSUE THREAD

**Issue by lkfun** [Aziteee/nonebot_plugin_reborn#4]
![微信截图_20221213173930](https://user-images.githubusercontent.com/25656788/207282721-6ad3af1d-e07d-40d4-b9f1-e22e49fcb336.png)

之前发现科特迪瓦的图片出不来，而且伊朗的图片出来后不显示黑色填充，后对比了一下源代码，
首先，伊朗是data.py中的国家或地区名字和https://fastly.jsdelivr.net/npm/echarts@4.9.0/map/js/world.js  中的国家或地区名字不匹配的问题。
举例如下：
https://github.com/Aziteee/nonebot_plugin_reborn/blob/1329be7cea8c747943b067463a8e8db2c217d853/nonebot_plugin_reborn/data.py#L847
这里的伊朗为Iran Islamic Rep.
而world.js中为 Iran
![iran](https://user-images.githubusercontent.com/25656788/207244747-c4f33b2f-6e54-4d68-bf8e-ed6619b348a5.png)

我全量核对了一下，建议改为下列这些，其中标注无的建议删除，因为在world.js中找不到。

Antigua and Barb.（建议data.py中的命名改为这个，下同）
Cape Verde
Bosnia and Herz.
无Aruba（建议删除该国家或地区，下同）
Brunei 
Bahamas
Cayman Is.
无Channel Islands
Central African Rep.
Congo
Dem. Rep. Congo
无Faroe Islands
Czech Rep.
Cyprus（只有南塞浦路斯）
Côte d'Ivoire
Dominican Rep.
Egypt 
Gambia 
无Hong Kong SAR China
Kyrgyzstan
Dem. Rep. Korea（朝鲜）
Korea （韩国）
Lao PDR
Iran
Saint Lucia
无Monaco
无Macao SAR China
N. Mariana Is.
无St. Martin (French part)
无Maldives
Fr. Polynesia
Russia
Solomon Is.
Slovakia
无San Marino
São Tomé and Principe
Syria
无Eswatini
Turkey
Venezuela
Yemen
无Kosovo
Micronesia
Macedonia
S. Sudan
无St. Kitts and Nevis
无St. Vincent and the Grenadines
U.S. Virgin Is.
无最后一个

另外科特迪瓦的问题，建议这儿改为双引号
https://github.com/Aziteee/nonebot_plugin_reborn/blob/1329be7cea8c747943b067463a8e8db2c217d853/nonebot_plugin_reborn/chart.py#L34

**Comment by Aziteee** [comment]
感谢issue，已修复bug
我没有直接改data.py，因为数据后续可能会有更新
